### ISSUE TITLE
& character in a tweet comes out as "&amp;" on IRC

### ISSUE THREAD

**Issue by dinkmaster** [Zarthus/irc-twitter-bot#1]
For example a tweet stating "Q&A starts in 5 minutes" will come out as "Q&amp;A starts in 5 minutes"

**Comment by Zarthus** [comment]
Hi dinkmaster,

When you upgrade to the newest version, running `bundle install` again should install the `HTMLEntities` dependency. 

This should fix problems like this and other forms of entities that were left encoded.
